title: VF
logo: "images/logo.jpg" # You can add own logo image.
description: Victor Férat Blog and Portfolio
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://vferat.github.io/" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Victor Férat
  bio: Hi, my name is Victor Férat. I'm a young neuroscientist who falled in love with Python.

# Contact links
#twitter: https://twitter.com/  #Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
github: https://github.com/vferat # Add your github handle
linkedin: https://www.linkedin.com/in/victor-ferat/ # Add your linkedin handle
instagram: https://www.instagram.com/v_ferat/ # Add your Instagram handle
email: victor.ferat@live.fr # Add your Email address

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: HOME # Add your hero title
#hero-subtitle: For those who love simplicity # Add your hero subtitle
hero-image: images/hero.jpg # Add background image in section hero

# Footer
footer-image: images/footer.jpg # Add background image in footer

# Comment Section (Disqus)
#disqus-identifier: https-vferat-github-io # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "UA-164007572-1" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jemoji

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed