name: Publish
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: build_and_commit
      name: Build and commit
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: './source'
        requirements_path: './requirements.txt'
        publish: false
    - id: ls
      name: List files
      run: ls ${{ steps.build_and_commit.outputs.artifact }}
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.build_and_commit.outputs.artifact }}
        destination_dir: docs