name: Publish
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: build_and_commit
      name: Build and commit
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: './source'
        requirements_path: './requirements.txt'
        publish: false
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: ${{ steps.build_and_commit.outputs.artifact }}