name: Publish
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Commit
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: './source'
        publish: false
    - name: Push changes
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ./
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAR_GLOBS_FILE: ".clear-target-files"